branches:
  only:
    - staging
    - master
    - trying


language: rust
rust:
  - stable
  - beta

script:
  - |
    if [[ $TRAVIS_RUST_VERSION == "stable" ]]
    then
      rustup component add rustfmt
      cargo fmt -- --check
    fi
  - cargo test --all-features --all-targets
  - cargo test --release
