[package]
name = "rowan"
version = "0.1.3"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees."

[dependencies]
parking_lot = "0.7.0"
text_unit = "0.1.5"
smol_str = "0.1.6"

[dev-dependencies]
m_lexer = "0.0.4"
